-- Insert sample companies
INSERT INTO companies (name, slug, description, logo_url, website_url, founded_year, industry, location, employee_count, funding_stage, total_funding, valuation) VALUES
('K7 Computing', 'k7-computing', 'Leading cybersecurity company providing comprehensive security solutions for businesses and individuals.', '/images/k7-security-logo.png', 'https://k7computing.com', 1991, 'Cybersecurity', 'Chennai, India', '500-1000', 'Private', 50000000, 200000000),
('Jammi Ayurveda', 'jammi-ayurveda', 'Traditional Ayurvedic medicine company focused on natural health and wellness products.', '/images/jammi-founder-logo.png', 'https://jammiayurveda.com', 2010, 'Healthcare', 'Hyderabad, India', '100-500', 'Series A', 10000000, 50000000),
('Watsan Envirotech', 'watsan-envirotech', 'Water purification and sanitation solutions for homes and communities.', '/images/watsan-logo.png', 'https://watsanenvirotech.com', 2015, 'Environmental Technology', 'Bangalore, India', '50-100', 'Seed', 2000000, 10000000),
('Milky Mist', 'milky-mist', 'Premium dairy products company known for quality paneer, curd, and dairy items.', '/images/milky-mist-logo.png', 'https://milkymist.in', 2009, 'Food & Beverages', 'Tamil Nadu, India', '1000-5000', 'IPO Ready', 100000000, 500000000),
('Organic Shandy', 'organic-shandy', 'Organic food products including vegetables, fruits, grains, and personal care items.', '/images/organic-shandy-logo.png', 'https://organicshandy.com', 2018, 'Organic Food', 'Kerala, India', '10-50', 'Bootstrap', 500000, 5000000);

-- Insert sample products
INSERT INTO products (company_id, name, slug, description, image_url, category, price, launch_date, features) VALUES
(1, 'K7 Total Security', 'k7-total-security', 'Complete antivirus and internet security solution for Windows, Mac, and mobile devices.', '/images/k7-total-security-logo.png', 'Security Software', 1999.00, '2020-01-15', '{"features": ["Real-time protection", "Firewall", "Anti-phishing", "Parental controls"]}'),
(2, 'Jammi Livercure Complex Forte', 'jammi-livercure-complex-forte', 'Ayurvedic liver tonic for detoxification and liver health improvement.', '/images/jammi-livercure-product.png', 'Ayurvedic Medicine', 299.00, '2019-06-01', '{"features": ["Natural ingredients", "Liver detox", "Digestive health", "No side effects"]}'),
(2, 'Jammi Kumkumadi Serum', 'jammi-kumkumadi-serum', 'Premium face serum with saffron and natural oils for glowing skin.', '/images/jammi-kumkumadi-serum-product.png', 'Skincare', 899.00, '2021-03-15', '{"features": ["Saffron extract", "Anti-aging", "Natural glow", "Suitable for all skin types"]}'),
(3, 'Watsan Home RO System', 'watsan-home-ro-system', 'Advanced reverse osmosis water purification system for homes.', '/images/watsan-household-purifier.png', 'Water Purification', 12999.00, '2020-08-01', '{"features": ["7-stage purification", "UV sterilization", "Mineral retention", "Smart indicators"]}'),
(4, 'Milky Mist Paneer', 'milky-mist-paneer', 'Fresh, soft paneer made from pure milk with no preservatives.', '/images/milky-mist-complete-range.png', 'Dairy Products', 120.00, '2015-01-01', '{"features": ["Fresh daily", "No preservatives", "High protein", "Vacuum packed"]}'),
(5, 'Organic Shandy Vegetables', 'organic-shandy-veggies-greens', 'Fresh organic vegetables grown without pesticides or chemicals.', '/images/organic-shandy-vegetables.png', 'Organic Vegetables', 150.00, '2019-01-01', '{"features": ["100% organic", "Pesticide-free", "Farm fresh", "Home delivery"]}');

-- Insert sample content
INSERT INTO content (title, slug, description, content_type, thumbnail_url, author_id, company_id, product_id, views, duration, published_at, status, tags) VALUES
('K7 Computing: Cybersecurity Innovation in India', 'k7-computing-cybersecurity-innovation', 'Deep dive into how K7 Computing became a leading cybersecurity company in India.', 'article', '/images/k7-website-screenshot.jpg', 1, 1, NULL, 1250, NULL, '2024-01-15 10:00:00', 'published', '["cybersecurity", "indian-startup", "technology"]'),
('The Rise of Ayurvedic Startups', 'rise-of-ayurvedic-startups', 'Exploring the growth of traditional medicine companies like Jammi Ayurveda.', 'article', '/images/jammi-website-homepage.jpeg', 1, 2, NULL, 890, NULL, '2024-01-20 14:30:00', 'published', '["ayurveda", "healthcare", "traditional-medicine"]'),
('Water Purification Technology Trends', 'water-purification-technology-trends', 'Latest innovations in water purification by companies like Watsan Envirotech.', 'video', '/images/watsan-terafil-purifier.png', 1, 3, NULL, 2100, 1800, '2024-01-25 09:15:00', 'published', '["water-tech", "environment", "innovation"]'),
('Milky Mist IPO Journey', 'milky-mist-ipo-journey', 'Analysis of Milky Mist''s path to going public and market expansion.', 'case-study', '/images/milky-mist-website-screenshot.png', 1, 4, NULL, 3200, NULL, '2024-02-01 11:00:00', 'published', '["ipo", "dairy-industry", "growth-story"]'),
('Organic Food Market in India', 'organic-food-market-india', 'Understanding the organic food ecosystem with insights from Organic Shandy.', 'podcast', '/images/organic-shandy-logo.png', 1, 5, NULL, 750, 2400, '2024-02-05 16:45:00', 'published', '["organic-food", "agriculture", "sustainability"]');
